[package]
name = "bellperson"
authors = [
  "dignifiedquire <me@dignifiedquire.com>",
  "Sean Bowe <ewillbefull@gmail.com>",
]
description = "zk-SNARK library"
documentation = "https://docs.rs/bellperson"
homepage = "https://github.com/filecoin-project/bellman"
license = "MIT/Apache-2.0"
repository = "https://github.com/filecoin-project/bellman"
version = "0.18.2"
readme = "README.md"
edition = "2018"

[dependencies]
bitvec = "0.22"
blake2s_simd = "0.5"
ff = "0.11.0"
group = "0.11.0"
rand_core = "0.6"
byteorder = "1"
log = "0.4.8"
lazy_static = "1.4.0"
rand = "0.8"
rayon = "1.5.0"
memmap = "0.7.0"
thiserror = "1.0.10"
num_cpus = "1"
crossbeam-channel = "0.5.0"
digest = "0.9.0"
itertools = "0.10.0"
bincode = "1.3.1"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.9"
blstrs = "0.4.0"
pairing = "0.21"
yastl = "0.1.2"

# cuda/opencl feature
rust-gpu-tools = { version = "0.5.0", optional = true, default-features = false }
ec-gpu = { version = "0.1.0", optional = true }
ec-gpu-gen = { version = "0.1.0", optional = true }
fs2 = { version = "0.4.3", optional = true }


[dev-dependencies]
hex-literal = "0.3"
rand_xorshift = "0.3"
env_logger = "0.9.0"
criterion = "0.3.2"
rand_chacha = "0.3"
csv = "1.1.5"
tempfile = "3.1.0"
subtle = "2.2.1"

[build-dependencies]
blstrs = "0.4.0"
execute = "0.2.9"
ec-gpu = { version = "0.1.0", optional = true }
ec-gpu-gen = { version = "0.1.0", optional = true }
hex = "0.4"
sha2 = "0.9"


[features]
default = ["groth16"]
cuda = ["rust-gpu-tools/cuda", "ec-gpu", "ec-gpu-gen", "fs2", "blstrs/gpu"]
opencl = ["rust-gpu-tools/opencl", "ec-gpu", "ec-gpu-gen", "fs2", "blstrs/gpu"]
groth16 = []

# This feature disables/modifies long running tests to make the suitable for code coverage
# reporting
_coverage = []

[[test]]
name = "mimc"
path = "tests/mimc.rs"
required-features = ["groth16"]

[[test]]
name = "groth16_aggregation"
path = "tests/groth16_aggregation.rs"
required-features = ["groth16"]

[badges]
maintenance = { status = "actively-developed" }

[[bench]]
name = "lc"
harness = false

[workspace]
members = [
  "verifier-bench"
]
